# do not build pull request from base repo twice (only build PRs of forks)
if: type != pull_request OR fork = true

language: python
python: 3.8

# setuptools-scm needs all tags in order to obtain a proper version
git:
  depth: false

env:
  global:
    # Note: TWINE_PASSWORD is set in Travis settings
    - TWINE_USERNAME=geostatframework
    - CIBW_BUILD="cp35-* cp36-* cp37-* cp38-*"
    - CIBW_SKIP="*_i686"  # skip linux 32bit for matplotlib
    # update setuptools to latest version
    - CIBW_BEFORE_BUILD="pip install -U setuptools"
    # testing with cibuildwheel
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest -v {project}/tests"

notifications:
  email:
    recipients:
    - info@geostat-framework.org

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" = windows ]]; then
        choco install python --version 3.8.0
        export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        ln -s /c/Python38/python.exe /c/Python38/python3.exe
    fi

install:
  - python3 -m pip install cibuildwheel==1.3.0

script:
  - python3 -m cibuildwheel --output-dir tmp_dist

stages:
  - test
  - coverage
  - name: deploy
    if: (NOT type IN (pull_request)) AND (repo = GeoStat-Framework/welltestpy)

jobs:
  include:
    - stage: test
      name: Test on Linux
      services: docker
    - stage: test
      name: Test on MacOS
      os: osx
      language: generic
    - stage: test
      name: Test on Windows
      os: windows
      language: shell

    - stage: coverage
      name: Coverage on Linux
      services: docker
      install: python3 -m pip install .[test] coveralls
      script:
        - python3 -m pytest --cov welltestpy --cov-report term-missing -v tests/
        - python3 -m coveralls

    # Test Deploy source distribution
    - stage: deploy
      name: Test Deploy
      install: python3 -m pip install -U setuptools wheel twine
      script: python3 setup.py sdist --formats=gztar bdist_wheel
      after_success:
       - python3 -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*

    # Deploy source distribution
    - stage: deploy
      name: Deploy to PyPI
      if: tag IS present
      install: python3 -m pip install -U setuptools wheel twine
      script: python3 setup.py sdist --formats=gztar bdist_wheel
      after_success: python3 -m twine upload --verbose --skip-existing dist/*
